Fix shellcheck errors
- add a Makefile as well

diff --git a/bin/chaws b/bin/chaws
--- a/bin/chaws
+++ b/bin/chaws
@@ -1,8 +1,19 @@
 #!/bin/bash
+# -*-* mode: sh-bash -*-
 
-set -feuo pipefail
-IFS=$'\n\t'
+set -o pipefail
+set -o errtrace
+trap 'err_handler $?' ERR
 
+err_handler() {
+    trap - ERR
+    let i=0 exit_status=$1
+    echo "Aborting on error $exit_status:"
+    echo "--------------------"
+    while caller $i; do ((i++)); done
+    exit $?
+}
+    
 #set -x
 
 # Produce short hash just as insurance in case the directory scheme
@@ -20,44 +31,48 @@ function args_to_dir {
     local -a dir_safe_args
     for arg in "$@"
     do
-	xlated=$(echo -n $arg | tr --delete --complement 'a-zA-Z0-9_')
-	dir_safe_args+=( $xlated  )
+	safe_arg=$(echo -n "$arg" | tr --delete --complement 'a-zA-Z0-9_')
+	dir_safe_args+=( $safe_arg  )
     done
 
-    join_by "/" ${dir_safe_args[@]}
+    join_by "/" "${dir_safe_args[@]}"
 }
 
 CHAWS_CACHE_DIR=${CHAWS_CACHE_DIR-.chaws-cache}
 
-cached_output_dir="${CHAWS_CACHE_DIR}/$(args_to_dir $@)/$(hexsum $@)"
 metadata_dir="${CHAWS_CACHE_DIR}/.metadata"
+mkdir -p "$metadata_dir"
 
-mkdir -p $cached_output_dir $metadata_dir
+cached_results_dir=${CHAWS_CACHE_DIR}/$(args_to_dir "$@")/$(hexsum "$@")
 
-cached_output=$cached_output_dir/output
+mkdir -p "$cached_results_dir"
 
-if [[ ! -f $cached_output || -n ${CHAWS_REFRESH+x} ]]
+cached_stdout=$cached_results_dir/stdout.out
+cached_stderr=$cached_results_dir/stderrr.out
+cached_return_code=$cached_results_dir/return-code
+cached_args=$cached_results_dir/args
+
+if [[ ! -f $cached_return_code || -n ${CHAWS_REFRESH+x} ]]
 then
-    cli_stdout=$(mktemp --tmpdir=$cached_output_dir 'cli_stdoutXXXXX.out')
+    cli_stdout=$(mktemp --tmpdir="$cached_results_dir" 'cli_stdoutXXXXX.out')
+    # shellcheck disable=SC2064
     trap "rm -f '$cli_stdout'" EXIT
-    cli_stderr=$cached_output_dir/stderr.out
-    rm -f $cli_stderr
+    rm -f "$cached_stderr"
 
     set +e
-    echo aws "$@" >"$cached_output_dir/args"
-    aws "$@" >$cli_stdout 2>$cli_stderr
+    echo aws "$@" >"$cached_args"
+    aws "$@" >"$cli_stdout" 2>"$cached_stderr"
     return_code=$?
-    echo $return_code >"$cached_output_dir/return-code"
+    echo $return_code >"$cached_return_code"
     set -e
     if [[ $return_code != 0 ]]
     then
-	cat 1>&2 $cli_stderr
+	cat 1>&2 "$cached_stderr"
 	exit $return_code
     else
-	mv $cli_stdout $cached_output
+	mv "$cli_stdout" "$cached_stdout"
     fi
 fi
 
-cat $cached_output
+cat "$cached_stdout"
 exit
-
